# .goreleaser.yml
version: 2
project_name: czds

before:
  hooks:
    - go mod tidy

builds:
  - id: czds
    main: ./cmd/
    binary: czds
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}

nfpms:
  - id: czds
    # Package info
    maintainer: lanrat
    homepage: https://github.com/lanrat/czds
    description: |-
      tools to interact with czds.icann.org
    # Supported formats
    formats:
      - deb
      - rpm
      - apk
      - archlinux

archives:
  - # This single archive definition handles all OSes.
    # The default format is 'tar.gz', which is used for linux and darwin.
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: ['zip'] # Override the format to 'zip' for Windows builds.

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'